version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: devtrackr_postgres
    restart: always
    environment:
      POSTGRES_DB: devtrackr
      POSTGRES_USER: devtrackr
      POSTGRES_PASSWORD: devtrackr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: devtrackr_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: devtrackr_backend
    command: sh entrypoint.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  celery:
    build: ./backend
    container_name: devtrackr_celery
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres_data: